---
- name: Deploy Blog Application
  hosts: local
  become: yes

  tasks:
    - name: Pull latest Docker images
      docker_image:
        name: "{{ item }}"
        pull: always
      loop:
        - nikhilguptaiiitb/frontend-app:latest
        - nikhilguptaiiitb/backend-app:latest

    - name: Stop running containers (if any)
      docker_compose:
        project_src: "{{ playbook_dir }}"
        state: absent

    - name: Start services using Docker Compose
      docker_compose:
        project_src: "{{ playbook_dir }}"
        state: present
