---
- name: Deploy Blog Application
  hosts: localhost
  become: yes

  tasks:
    - name: Pull latest Docker images
      community.general.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - nikhilguptaiiitb/frontend-app:latest
        - nikhilguptaiiitb/backend-app:latest

    - name: Stop running containers (if any)
      community.general.docker_compose:
        project_src: "{{ playbook_dir }}"
        state: absent

    - name: Start services using Docker Compose
      community.general.docker_compose:
        project_src: "{{ playbook_dir }}"
        state: present
