---
- name: Deploy Blog Application
  hosts: local
  become: false
  tasks:
    - name: Pull and Run Docker Compose
      docker_compose:
        project_src: "{{ playbook_dir }}"
        state: present
        pull: yes
        restarted: yes
