---
- name: Deploy Blog Application
  hosts: local
  become: false
  tasks:
    - name: Install Docker Compose if not present
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'
      when: ansible_os_family == "Debian"

    - name: Pull and Run Docker Compose
      docker_compose:
        project_src: "{{ playbook_dir }}"
        state: present
        pull: yes
        restarted: yes
      become: false
